[package]
name = "HiddifyDesktop"
version = "0.1.0"
description = "clash verge"
authors = ["zzzgydi"]
license = "GPL-3.0"
repository = "https://github.com/zzzgydi/clash-verge.git"
default-run = "HiddifyDesktop"
edition = "2021"
build = "build.rs"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
warp = "0.3"
which = "4.2.2"
anyhow = "1.0"
dirs = "4.0.0"
open = "3.2.0"
log = "0.4.14"
ctrlc = "3.2.3"
dunce = "1.0.2"
log4rs = "1.0.0"
nanoid = "0.4.0"
chrono = "0.4.19"
sysinfo = "0.27"
sysproxy = "0.2"
rquickjs = "0.1.7"
serde_json = "1.0"
serde_yaml = "0.9"
auto-launch = "0.4"
once_cell = "1.14.0"
port_scanner = "0.1.5"
delay_timer = "0.11.1"
parking_lot = "0.12.0"
tokio = { version = "1", features = ["full"] }
async-std = { version = "1", features = ["attributes", "tokio1"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json","socks","blocking"] }
tauri = { version = "1.1.1", features = ["global-shortcut-all", "process-all", "shell-all", "system-tray", "updater", "window-all"] }
tauri-runtime-wry = { version = "0.12" }
window-vibrancy = { version = "0.3.0" }
window-shadows = { version = "0.2.0" }
patch = "0.7.0"
interprocess = "1.2.1"
tauri-utils = "1.2.1"
futures = { version = "0.3", features = ["compat"] }
dirs-next = "2.0.0"
rayon = "1.6.1"
roxmltree = "0.18.0"
url = "2.3.1"
md5 = "0.7.0"
iter-read = "0.3.1"
online = "4.0.0"

[target.'cfg(windows)'.dependencies]
runas = "0.2.1"
deelevate = "0.2.0"
winreg = { version = "0.10", features = ["transactions"] }
windows-sys = { version = "0.36", features = ["Win32_System_LibraryLoader", "Win32_System_SystemInformation"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
verge-dev = []
default-meta = []

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
